name: lab3 actions test
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: System info
        run: |
          echo "$(uname -a)"
          echo "$(lscpu)"
